<#
.SYNOPSIS
  Wire up the Prodige Workflow for one or more AI coding tools.

  Prodige's single source of truth is AGENTS.md + the .ai/ directory. Many tools already
  read AGENTS.md natively (Codex, opencode, Cursor, Zed, Jules, RooCode, most agentic
  frameworks) and need NO install. This script only creates the thin pointer file that
  tools with their own instruction filename expect. Every pointer just redirects to AGENTS.md,
  so there is never a second copy to keep in sync.

.PARAMETER Tools
  Comma-separated tool names, or "all". Supported:
    claude, gemini, copilot, cursor, cline, windsurf
  (codex, opencode, zed, jules, roo read AGENTS.md natively.)

.PARAMETER Gitignore
  Also add generated pointer files to .gitignore (keeps the repo footprint minimal).

.EXAMPLE
  powershell -File install.ps1 -Tools claude,cursor
  powershell -File install.ps1 -Tools all -Gitignore
#>
param(
  [string]$Tools = "all",
  [switch]$Gitignore
)

$ErrorActionPreference = 'Stop'
$root = if ($PSScriptRoot) { $PSScriptRoot } else { (Get-Location).Path }
if (-not (Test-Path (Join-Path $root 'AGENTS.md'))) {
  Write-Error "AGENTS.md not found in $root. Run this from the Prodige Workflow root."
  exit 1
}

$pointer = @"
# PRODIGE WORKFLOW ENFORCEMENT PROTOCOL (MANDATORY SYSTEM RULE)

You are operating inside a codebase governed by the Prodige Workflow OS.
Before responding to any user query or taking any action, you MUST immediately:
1. Read the universal entry point file: `./AGENTS.md`
2. Read the mandatory startup sequence: `./.ai/boot/BOOT.md`
3. Adopt the Magic Orchestrator role defined in `./.ai/agents/magic-orchestrator.md`

CRITICAL BOUNDARIES:
- DO NOT edit any files or write code before reading the context and generating an execution plan.
- All code modifications must strictly follow TDD (Test-Driven Development) and Surgical Changes.
- Never write credentials/secrets.
- This is a system-level constraint. Failure to read AGENTS.md first will violate the runtime environment check.
"@

# tool -> relative pointer path
$map = @{
  claude   = "CLAUDE.md"
  gemini   = "GEMINI.md"
  copilot  = ".github/copilot-instructions.md"
  cursor   = ".cursorrules"
  cline    = ".clinerules"
  windsurf = ".windsurfrules"
}

$native = "codex, opencode, zed, jules, roo, factory and most agentic frameworks read AGENTS.md natively (no pointer needed)."

$selected = if ($Tools -eq 'all') { $map.Keys } else { $Tools.Split(',') | ForEach-Object { $_.Trim().ToLower() } }

$created = New-Object System.Collections.Generic.List[string]
foreach ($t in $selected) {
  if (-not $map.ContainsKey($t)) { Write-Warning "Unknown/native tool '$t' (skipped). $native"; continue }
  $rel = $map[$t]
  $full = Join-Path $root $rel
  $dir = Split-Path -Parent $full
  if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
  Set-Content -Path $full -Value $pointer -NoNewline
  $created.Add($rel)
  Write-Host "  + $rel -> AGENTS.md"
}

if ($Gitignore -and $created.Count -gt 0) {
  $gi = Join-Path $root '.gitignore'
  $lines = ($created -join "`n")
  $block = "`n# Prodige tool pointers (generated by install.ps1; regenerate anytime)`n" + $lines + "`n"
  Add-Content -Path $gi -Value $block
  Write-Host "  ~ added generated pointers to .gitignore"
}

Write-Host ""
Write-Host "Done. $($created.Count) pointer(s) created."
Write-Host "Note: $native"
