#!/usr/bin/env bash
# Wire up the Prodige Workflow for one or more AI coding tools.
#
# Single source of truth: AGENTS.md + .ai/.
# Many tools read AGENTS.md natively; these pointers improve recall for tools
# that prefer their own rule locations. They are not a hard runtime sandbox.
#
# Usage:
#   ./install.sh [tools] [--gitignore]
#     tools: comma-separated (claude,gemini,copilot,cursor,cline,windsurf,devin)
#            or "all" (default)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[ -f "$ROOT/AGENTS.md" ] || { echo "AGENTS.md not found in $ROOT. Run from the Prodige Workflow root." >&2; exit 1; }

TOOLS="all"
GITIGNORE=0
for arg in "$@"; do
  case "$arg" in
    --gitignore) GITIGNORE=1 ;;
    *) TOOLS="$arg" ;;
  esac
done

read -r -d '' POINTER <<'EOF' || true
# PRODIGE WORKFLOW POINTER

You are operating inside a codebase governed by the Prodige Workflow.
Before responding to any user query or taking any action, read and follow:
1. `./AGENTS.md`
2. `./.ai/boot/BOOT.md`
3. `./.ai/commands/registry.json`

Use `node .ai/scripts/prodige-mcp.js` when MCP tools are available.
Do not edit code before loading context, planning, and respecting HITL gates.
EOF

NATIVE="Codex, opencode, RooCode, Devin, Windsurf, and many agentic frameworks can read AGENTS.md natively; pointers improve recall but are not hard enforcement."

pointer_paths() {
  case "$1" in
    claude)   echo "CLAUDE.md" ;;
    gemini)   echo "GEMINI.md" ;;
    copilot)  echo ".github/copilot-instructions.md" ;;
    cursor)   echo ".cursor/rules/prodige.mdc .cursorrules" ;;
    cline)    echo ".clinerules/prodige.md" ;;
    windsurf) echo ".windsurf/rules/prodige.md .windsurfrules" ;;
    devin)    echo ".devin/rules/prodige.md" ;;
    *)        echo "" ;;
  esac
}

if [ "$TOOLS" = "all" ]; then
  SELECTED="claude gemini copilot cursor cline windsurf devin"
else
  SELECTED="$(echo "$TOOLS" | tr ',' ' ')"
fi

CREATED=()
for t in $SELECTED; do
  rels="$(pointer_paths "$(echo "$t" | tr '[:upper:]' '[:lower:]')")"
  if [ -z "$rels" ]; then
    echo "Unknown/native tool '$t' (skipped). $NATIVE" >&2
    continue
  fi
  for rel in $rels; do
    dir="$(dirname "$ROOT/$rel")"
    if [ -f "$dir" ]; then mv "$dir" "$dir.legacy"; fi
    mkdir -p "$dir"
    printf '%s\n' "$POINTER" > "$ROOT/$rel"
    CREATED+=("$rel")
    echo "  + $rel -> AGENTS.md"
  done
done

if [ "$GITIGNORE" -eq 1 ] && [ "${#CREATED[@]}" -gt 0 ]; then
  {
    echo ""
    echo "# Prodige tool pointers (generated by install.sh; regenerate anytime)"
    for c in "${CREATED[@]}"; do echo "$c"; done
  } >> "$ROOT/.gitignore"
  echo "  ~ added generated pointers to .gitignore"
fi

echo ""
echo "Done. ${#CREATED[@]} pointer(s) created."
echo "Note: $NATIVE"
