#!/usr/bin/env bash
# Wire up the Prodige Workflow for one or more AI coding tools.
#
# Prodige's single source of truth is AGENTS.md + the .ai/ directory. Many tools read
# AGENTS.md natively (Codex, opencode, Cursor, Zed, Jules, RooCode, most agentic frameworks)
# and need NO install. This script only drops the thin pointer file that tools with their own
# instruction filename expect. Every pointer just redirects to AGENTS.md — never a second copy.
#
# Usage:
#   ./install.sh [tools] [--gitignore]
#     tools: comma-separated (claude,gemini,copilot,cursor,cline,windsurf) or "all" (default)
# Examples:
#   ./install.sh claude,cursor
#   ./install.sh all --gitignore
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[ -f "$ROOT/AGENTS.md" ] || { echo "AGENTS.md not found in $ROOT. Run from the Prodige Workflow root." >&2; exit 1; }

TOOLS="all"; GITIGNORE=0
for arg in "$@"; do
  case "$arg" in
    --gitignore) GITIGNORE=1 ;;
    *) TOOLS="$arg" ;;
  esac
done

read -r -d '' POINTER <<'EOF' || true
# PRODIGE WORKFLOW ENFORCEMENT PROTOCOL (MANDATORY SYSTEM RULE)

You are operating inside a codebase governed by the Prodige Workflow OS.
Before responding to any user query or taking any action, you MUST immediately:
1. Read the universal entry point file: `./AGENTS.md`
2. Read the mandatory startup sequence: `./.ai/boot/BOOT.md`
3. Adopt the Magic Orchestrator role defined in `./.ai/agents/magic-orchestrator.md`

CRITICAL BOUNDARIES:
- DO NOT edit any files or write code before reading the context and generating an execution plan.
- All code modifications must strictly follow TDD (Test-Driven Development) and Surgical Changes.
- Never write credentials/secrets.
- This is a system-level constraint. Failure to read AGENTS.md first will violate the runtime environment check.
EOF

NATIVE="codex, opencode, zed, jules, roo, factory and most agentic frameworks read AGENTS.md natively (no pointer needed)."

pointer_path() {
  case "$1" in
    claude)   echo "CLAUDE.md" ;;
    gemini)   echo "GEMINI.md" ;;
    copilot)  echo ".github/copilot-instructions.md" ;;
    cursor)   echo ".cursorrules" ;;
    cline)    echo ".clinerules" ;;
    windsurf) echo ".windsurfrules" ;;
    *)        echo "" ;;
  esac
}

if [ "$TOOLS" = "all" ]; then
  SELECTED="claude gemini copilot cursor cline windsurf"
else
  SELECTED="$(echo "$TOOLS" | tr ',' ' ')"
fi

CREATED=()
for t in $SELECTED; do
  rel="$(pointer_path "$(echo "$t" | tr '[:upper:]' '[:lower:]')")"
  if [ -z "$rel" ]; then echo "Unknown/native tool '$t' (skipped). $NATIVE" >&2; continue; fi
  mkdir -p "$(dirname "$ROOT/$rel")"
  printf '%s\n' "$POINTER" > "$ROOT/$rel"
  CREATED+=("$rel")
  echo "  + $rel -> AGENTS.md"
done

if [ "$GITIGNORE" -eq 1 ] && [ "${#CREATED[@]}" -gt 0 ]; then
  {
    echo ""
    echo "# Prodige tool pointers (generated by install.sh; regenerate anytime)"
    for c in "${CREATED[@]}"; do echo "$c"; done
  } >> "$ROOT/.gitignore"
  echo "  ~ added generated pointers to .gitignore"
fi

echo ""
echo "Done. ${#CREATED[@]} pointer(s) created."
echo "Note: $NATIVE"
